repos:
  # -------------------------------
  # 1. clang-format (code style)
  # -------------------------------
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        name: clang-format
        files: \.(cpp|hpp|cc|cxx|h)$
        args:
          - --style=file

  # -------------------------------
  # 2. clang-tidy (static analysis)
  # -------------------------------
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        language: system
        types: [c++]
        files: \.(cpp|cc|cxx|h|hpp)$
        args:
          - -p=build
          - --config-file=.clang-tidy
          - --quiet

  # -------------------------------
  # 3. cppcheck (extra safety)
  # -------------------------------
      - id: cppcheck
        name: cppcheck
        entry: cppcheck
        language: system
        types: [c++]
        files: \.(cpp|cc|cxx|h|hpp)$
        args:
          - --enable=all
          - --inconclusive
          - --quiet
